metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    - filesystem
    - fsstat
  enabled: true
  period: 10s
  processes: ['.*']
  cpu.metrics:
    - percentages
    - normalized_percentages
  core.metrics:
    - percentages

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - image
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s
  hosts: ["http://nginx/nginx_status"]

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - cluster_stats
  period: 10s
  hosts: ["http://elasticsearch:9200"]

- module: kibana
  metricsets: ["status"]
  period: 10s
  hosts: ["http://kibana:5601"]

processors:
- add_host_metadata: ~
- add_cloud_metadata: ~
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

fields:
  environment: development
  
fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "metricbeat-%{+yyyy.MM.dd}"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0600 