filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields:
    log_type: nginx_access
    environment: development
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  
- type: log
  enabled: true
  paths:
    - /var/log/nginx/error.log
  fields:
    log_type: nginx_error
    environment: development
  fields_under_root: true
  multiline.pattern: '^\d{4}/\d{2}/\d{2}'
  multiline.negate: true
  multiline.match: after

- type: docker
  enabled: true
  containers.ids:
    - '*'
  containers.path: "/var/lib/docker/containers"
  containers.stream: "all"
  decode_json_fields.fields: ["message"]
  decode_json_fields.target: ""
  decode_json_fields.overwrite_keys: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_cloud_metadata: ~
- add_docker_metadata: ~
- timestamp:
    field: time_local
    layouts:
      - '02/Jan/2006:15:04:05 -0700'
    test:
      - '25/May/2023:10:30:45 +0000'

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "filebeat-nginx-%{+yyyy.MM.dd}"
  template.name: "filebeat-nginx"
  template.pattern: "filebeat-nginx-*"
  template.settings:
    index.number_of_shards: 1
    index.codec: best_compression

setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644 