http.host: "0.0.0.0"
http.port: 9600
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# Pipeline configuration
pipeline.workers: 2
pipeline.batch.size: 1000
pipeline.batch.delay: 50

# Monitoring
monitoring.enabled: false
xpack.monitoring.enabled: false

# Logging
log.level: info
path.logs: /usr/share/logstash/logs

# Dead letter queue
dead_letter_queue.enable: true
path.dead_letter_queue: /usr/share/logstash/data/dead_letter_queue

# Performance tuning
config.reload.automatic: true
config.reload.interval: 3s 